### ISSUE TITLE
CreateSite needs a timeout

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/worona-dashboard#54]
If you add a site in the `Add Site` screen and the server is down, the users keeps waiting indefinitely. 

Once the server is up again, it doesn't create the site (the request was sent before the server was up) but the UI keeps waiting for the server response:
![screen shot 2016-10-19 at 12 17 28](https://cloud.githubusercontent.com/assets/3305402/19515031/1977f7da-95f6-11e6-8fd9-7de9a0035d4b.png)

A possible solution is to add a timeout and retrieve `CREATE_SITE_FAILED`.
Another solution would be to wait for a `CONNECTION_SUCCEED` like the `Register` screen does.

**Comment by Akronix** [comment]
We'll add a helper waitForConnectionEstablished in the accounts package in order to sagas to be blocked  in case of lost connection

**Comment by Akronix** [comment]
This is paused as it's not being a priority for the time being.

**Comment by Akronix** [comment]
The problem here is that the server logout the user when user loses the connection, but the client hasn't registered any LOGOUT action and, therefore, user hasn't logout for the client part.
Then, after waitForConnectionEstablished saga helper has been added, flow is as follows:
1. user go to add-site
3. user lose connection
4. user fills and sends form
5. server reconnects
6. server throws a NOT_LOGGED_IN error.
